version: 2.0
jobs:
  test:
    docker:
      - image: grameaway/codechan
    steps:
      - checkout
      - run:
          name: The python latest
          command: python tests.py
      - store_test_results:
          path: build/test-results

workflows:
  version: 2
  flow:
    jobs:
      - test
