version: 2.0
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: The python latest
          command: python tests.py

workflows:
  version: 2
  flow:
    jobs:
      - test
